### ISSUE TITLE
Add optional closing comment?

### ISSUE THREAD

**Issue by himedlooff** [himedlooff/doxray#7]
I'm wondering if it would be nice to have a closing Dox-ray comment which would basically allow you to ignore stuff in a file. For example:

``` css
/* doxray
    name: button, duh
*/
.btn { ... }

/* end-doxray */

/* Some other code you don't want to document */
...

/* doxray
    name: a different button or thing you want to document
*/
.btn__different { ... }

```

In the above example if you didn't have that ending Dox-ray comment `/* end-doxray */` you'd get `/* Some other code you don't want to document */` as part of the "button, duh" code. Boooo! Who wants that? No one.
